# Site
title:              Jorge Reyes Vargas
bio:                'Un contenedor de variables.'
description:        "Blog personal, el cual a modo de contenedor de variables, pretende describir cada una de mis aficiones y experiencias sobre estás mismas."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo1.png'
background:         'assets/img/backg.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             es_CO
url:                https://jarvars.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   https-jarvars-github-io

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-98491146-1
  verify:           UA-98491146-1
  #ad-client:
  #ad-slot:
bing-verify:        E048A84BFA40794D5B4E5B20BECEBDB6
#email:
twitter:            jar_vars
#facebook:           jarvars
github-url:         jarvars
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           jarvars
#xing:              username
#instagram:         jarvars
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
steam:              jarvars
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
